resources:
- name: code-source
  type: git
  source:
     uri: https://github.com/skyline9002/PivotalPoc
     branch: master
- name: pcf
  type: cf
  source:
     api: https://api.run.pivotal.io
     skip_cert_check: false
     username: xxxxxxx
     password: xxxxxxx
     organization: pivotal-simon-huang
     space: development

jobs:
-  name: aspnetcore-unit-tests
   plan:
     - get: code-source
       trigger: true
     - task: run-tests
       privileged: true
       config:
          platform: linux
          inputs:
          - name: code-source
          image_resource:
            type: docker-image
            source:
              repository: microsoft/aspnetcore-build
          run:
             path: sh
             args:
             - -exc
             - |
               cd ./code-source/Concourse.Test
               dotnet restore
               dotnet test

-  name: deploy-to-prod
   plan:
     - get: code-source
       trigger: true
       passed: [aspnetcore-unit-tests]
     - put: pcf
       params:
         manifest: code-source/manifest.yml